import { GeneralCalendarEvent } from "../types/calendar";

const now = new Date();

class BangkokDateHelper {
  private date: Date;
  constructor(days: number, hourBangkok: number, minuteBangkok: number) {
    // Lock baseline to a fixed date (July 14, 2026) to prevent dates from dynamically floating/sliding
    const baseDate = new Date("2026-07-14T00:00:00+07:00");
    const bangkokDateStr = baseDate.toLocaleDateString("en-CA", { timeZone: "Asia/Bangkok" });
    const [y, m, d] = bangkokDateStr.split("-").map(Number);
    // hourBangkok in Asia/Bangkok (+7) converts to (hourBangkok - 7) in UTC
    this.date = new Date(Date.UTC(y, m - 1, d + days, hourBangkok - 7, minuteBangkok, 0, 0));
  }
  toISOString(): string {
    return this.date.toISOString();
  }
  toString(): string {
    return this.date.toLocaleString("th-TH", {
      timeZone: "Asia/Bangkok",
      weekday: "short",
      day: "numeric",
      month: "short",
      year: "numeric",
      hour: "2-digit",
      minute: "2-digit",
    }) + " น.";
  }
}

function offsetDays(days: number, hour = 9, minute = 0) {
  return new BangkokDateHelper(days, hour, minute);
}


// ─────────────────────────────────────────────────────────────────────────────
// TECH-FOCUSED CALENDAR DATABASE
// Scope: US Tech + International Tech stocks with market impact on AI/Semis
// NO Thai stocks by default. Thai stocks are out of scope for this system.
// ─────────────────────────────────────────────────────────────────────────────
export const CALENDAR_DATABASE: GeneralCalendarEvent[] = [

  // ═══════════════════════════════════════════════════════════════
  // SECTION A: MACRO EVENTS (US-focused, tech-relevant)
  // ═══════════════════════════════════════════════════════════════
  {
    id: "econ-cpi-us-q3-1",
    title: "US CPI (YoY) — Consumer Price Index",
    type: "economic",
    importance: "high",
    announcedAt: offsetDays(2, 20, 30).toISOString(), // +2 days 20:30 Thai
    timeThai: offsetDays(2, 20, 30).toISOString(),
    actual: null,
    forecast: "3.2%",
    previous: "3.3%",
    revision: null,
    country: "US",
    status: "confirmed",
    source: {
      source: "U.S. Bureau of Labor Statistics",
      sourceUrl: "https://www.bls.gov/cpi/",
      fetchedAt: now.toISOString(),
      timezone: "EST",
    },
  },
  {
    id: "econ-fed-rate-decision-1",
    title: "FOMC Interest Rate Decision",
    type: "economic",
    importance: "high",
    announcedAt: offsetDays(5, 2, 0).toISOString(), // +5 days 02:00 Thai
    timeThai: offsetDays(5, 2, 0).toISOString(),
    actual: null,
    forecast: "5.25%",
    previous: "5.50%",
    revision: null,
    country: "US",
    status: "confirmed",
    source: {
      source: "Federal Reserve Board",
      sourceUrl: "https://www.federalreserve.gov/",
      fetchedAt: now.toISOString(),
      timezone: "EST",
    },
  },
  {
    id: "econ-nonfarm-1",
    title: "Non-Farm Payrolls (NFP)",
    type: "economic",
    importance: "high",
    announcedAt: offsetDays(7, 20, 30).toISOString(),
    timeThai: offsetDays(7, 20, 30).toISOString(),
    actual: null,
    forecast: "185K",
    previous: "206K",
    revision: null,
    country: "US",
    status: "confirmed",
    source: {
      source: "U.S. Bureau of Labor Statistics",
      sourceUrl: "https://www.bls.gov/",
      fetchedAt: now.toISOString(),
      timezone: "EST",
    },
  },
  {
    id: "econ-gdp-q2-advance",
    title: "US GDP (QoQ) — Q2 Advance Estimate",
    type: "economic",
    importance: "high",
    announcedAt: offsetDays(10, 20, 30).toISOString(),
    timeThai: offsetDays(10, 20, 30).toISOString(),
    actual: null,
    forecast: "2.4%",
    previous: "1.4%",
    revision: null,
    country: "US",
    status: "confirmed",
    source: {
      source: "U.S. Bureau of Economic Analysis",
      sourceUrl: "https://www.bea.gov/",
      fetchedAt: now.toISOString(),
      timezone: "EST",
    },
  },
  {
    id: "econ-pce-deflator-1",
    title: "Core PCE Price Index (Fed's Preferred Inflation Gauge)",
    type: "economic",
    importance: "high",
    announcedAt: offsetDays(12, 20, 30).toISOString(),
    timeThai: offsetDays(12, 20, 30).toISOString(),
    actual: null,
    forecast: "2.6%",
    previous: "2.7%",
    revision: null,
    country: "US",
    status: "confirmed",
    source: {
      source: "U.S. Bureau of Economic Analysis",
      sourceUrl: "https://www.bea.gov/",
      fetchedAt: now.toISOString(),
      timezone: "EST",
    },
  },
  {
    id: "econ-jobless-claims-1",
    title: "Initial Jobless Claims",
    type: "economic",
    importance: "medium",
    announcedAt: offsetDays(1, 20, 30).toISOString(),
    timeThai: offsetDays(1, 20, 30).toISOString(),
    actual: null,
    forecast: "232K",
    previous: "228K",
    revision: null,
    country: "US",
    status: "confirmed",
    source: {
      source: "U.S. Department of Labor",
      sourceUrl: "https://www.dol.gov/",
      fetchedAt: now.toISOString(),
      timezone: "EST",
    },
  },
  {
    id: "econ-ism-manufacturing-1",
    title: "ISM Manufacturing PMI",
    type: "economic",
    importance: "medium",
    announcedAt: offsetDays(14, 22, 0).toISOString(),
    timeThai: offsetDays(14, 22, 0).toISOString(),
    actual: null,
    forecast: "49.5",
    previous: "48.5",
    revision: null,
    country: "US",
    status: "confirmed",
    source: {
      source: "Institute for Supply Management",
      sourceUrl: "https://www.ismworld.org/",
      fetchedAt: now.toISOString(),
      timezone: "EST",
    },
  },
  {
    id: "econ-10y-yield-auction",
    title: "US 10-Year Treasury Note Auction",
    type: "economic",
    importance: "medium",
    announcedAt: offsetDays(8, 2, 0).toISOString(),
    timeThai: offsetDays(8, 2, 0).toISOString(),
    actual: null,
    forecast: "4.45%",
    previous: "4.38%",
    revision: null,
    country: "US",
    status: "confirmed",
    source: {
      source: "U.S. Treasury",
      sourceUrl: "https://home.treasury.gov/",
      fetchedAt: now.toISOString(),
      timezone: "EST",
    },
  },

  // ═══════════════════════════════════════════════════════════════
  // SECTION B: US TECH EARNINGS — Semiconductors / AI / Cloud
  // ═══════════════════════════════════════════════════════════════
  {
    id: "earn-nvda-q2-2025",
    symbol: "NVDA",
    type: "earnings",
    announcedAt: offsetDays(3, 4, 20).toISOString(), // After US market close (AMC)
    timeThai: offsetDays(3, 4, 20).toISOString(),
    importance: "high",
    revenueActual: null,
    revenueForecast: "28.6B",
    revenuePrevious: "26.0B",
    epsActual: null,
    epsForecast: "0.64",
    epsPrevious: "0.59",
    eventTypeName: "Earnings",
    status: "confirmed",
    source: {
      source: "NVIDIA Investor Relations",
      sourceUrl: "https://investor.nvidia.com/",
      fetchedAt: now.toISOString(),
      timezone: "EST",
    },
  },
  {
    id: "earn-aapl-q3-2025",
    symbol: "AAPL",
    type: "earnings",
    announcedAt: offsetDays(6, 4, 0).toISOString(),
    timeThai: offsetDays(6, 4, 0).toISOString(),
    importance: "high",
    revenueActual: null,
    revenueForecast: "84.3B",
    revenuePrevious: "81.8B",
    epsActual: null,
    epsForecast: "1.24",
    epsPrevious: "1.15",
    eventTypeName: "Earnings",
    status: "confirmed",
    source: {
      source: "Apple Investor Relations",
      sourceUrl: "https://investor.apple.com/",
      fetchedAt: now.toISOString(),
      timezone: "EST",
    },
  },
  {
    id: "earn-msft-q4-fy25",
    symbol: "MSFT",
    type: "earnings",
    announcedAt: offsetDays(4, 4, 0).toISOString(),
    timeThai: offsetDays(4, 4, 0).toISOString(),
    importance: "high",
    revenueActual: null,
    revenueForecast: "64.8B",
    revenuePrevious: "61.9B",
    epsActual: null,
    epsForecast: "3.10",
    epsPrevious: "2.94",
    eventTypeName: "Earnings",
    status: "confirmed",
    source: {
      source: "Microsoft Investor Relations",
      sourceUrl: "https://www.microsoft.com/en-us/investor",
      fetchedAt: now.toISOString(),
      timezone: "EST",
    },
  },
  {
    id: "earn-googl-q2-2025",
    symbol: "GOOGL",
    type: "earnings",
    announcedAt: offsetDays(5, 4, 30).toISOString(),
    timeThai: offsetDays(5, 4, 30).toISOString(),
    importance: "high",
    revenueActual: null,
    revenueForecast: "84.2B",
    revenuePrevious: "80.5B",
    epsActual: null,
    epsForecast: "1.85",
    epsPrevious: "1.89",
    eventTypeName: "Earnings",
    status: "confirmed",
    source: {
      source: "Alphabet Investor Relations",
      sourceUrl: "https://abc.xyz/investor/",
      fetchedAt: now.toISOString(),
      timezone: "EST",
    },
  },
  {
    id: "earn-meta-q2-2025",
    symbol: "META",
    type: "earnings",
    announcedAt: offsetDays(5, 4, 0).toISOString(),
    timeThai: offsetDays(5, 4, 0).toISOString(),
    importance: "high",
    revenueActual: null,
    revenueForecast: "38.7B",
    revenuePrevious: "36.5B",
    epsActual: null,
    epsForecast: "4.72",
    epsPrevious: "4.71",
    eventTypeName: "Earnings",
    status: "confirmed",
    source: {
      source: "Meta Platforms Investor Relations",
      sourceUrl: "https://investor.fb.com/",
      fetchedAt: now.toISOString(),
      timezone: "EST",
    },
  },
  {
    id: "earn-amzn-q2-2025",
    symbol: "AMZN",
    type: "earnings",
    announcedAt: offsetDays(7, 4, 0).toISOString(),
    timeThai: offsetDays(7, 4, 0).toISOString(),
    importance: "high",
    revenueActual: null,
    revenueForecast: "148.5B",
    revenuePrevious: "143.3B",
    epsActual: null,
    epsForecast: "1.03",
    epsPrevious: "0.98",
    eventTypeName: "Earnings",
    status: "confirmed",
    source: {
      source: "Amazon Investor Relations",
      sourceUrl: "https://ir.aboutamazon.com/",
      fetchedAt: now.toISOString(),
      timezone: "EST",
    },
  },
  {
    id: "earn-amd-q2-2025",
    symbol: "AMD",
    type: "earnings",
    announcedAt: offsetDays(9, 4, 30).toISOString(),
    timeThai: offsetDays(9, 4, 30).toISOString(),
    importance: "high",
    revenueActual: null,
    revenueForecast: "6.3B",
    revenuePrevious: "5.47B",
    epsActual: null,
    epsForecast: "0.68",
    epsPrevious: "0.47",
    eventTypeName: "Earnings",
    status: "confirmed",
    source: {
      source: "AMD Investor Relations",
      sourceUrl: "https://ir.amd.com/",
      fetchedAt: now.toISOString(),
      timezone: "EST",
    },
  },
  {
    id: "earn-tsla-q2-2025",
    symbol: "TSLA",
    type: "earnings",
    announcedAt: offsetDays(-1, 4, 0).toISOString(), // Already released
    timeThai: offsetDays(-1, 4, 0).toISOString(),
    importance: "high",
    revenueActual: "25.7B",
    revenueForecast: "24.8B",
    revenuePrevious: "25.2B",
    epsActual: "0.52",
    epsForecast: "0.48",
    epsPrevious: "0.45",
    eventTypeName: "Earnings",
    guidance: "FY2025 vehicle deliveries guidance reaffirmed at 1.8-2.0M",
    status: "confirmed",
    source: {
      source: "Tesla Investor Relations",
      sourceUrl: "https://ir.tesla.com/",
      fetchedAt: now.toISOString(),
      timezone: "EST",
    },
  },
  {
    id: "earn-avgo-q3-fy25",
    symbol: "AVGO",
    type: "earnings",
    announcedAt: offsetDays(15, 4, 30).toISOString(),
    timeThai: offsetDays(15, 4, 30).toISOString(),
    importance: "high",
    revenueActual: null,
    revenueForecast: "13.8B",
    revenuePrevious: "12.49B",
    epsActual: null,
    epsForecast: "1.06",
    epsPrevious: "1.05",
    eventTypeName: "Earnings",
    status: "confirmed",
    source: {
      source: "Broadcom Investor Relations",
      sourceUrl: "https://investors.broadcom.com/",
      fetchedAt: now.toISOString(),
      timezone: "EST",
    },
  },
  {
    id: "earn-mu-q4-fy25",
    symbol: "MU",
    type: "earnings",
    announcedAt: offsetDays(11, 4, 30).toISOString(),
    timeThai: offsetDays(11, 4, 30).toISOString(),
    importance: "high",
    revenueActual: null,
    revenueForecast: "8.6B",
    revenuePrevious: "8.05B",
    epsActual: null,
    epsForecast: "1.48",
    epsPrevious: "1.30",
    eventTypeName: "Earnings",
    status: "confirmed",
    source: {
      source: "Micron Technology Investor Relations",
      sourceUrl: "https://investors.micron.com/",
      fetchedAt: now.toISOString(),
      timezone: "EST",
    },
  },
  {
    id: "earn-intc-q2-2025",
    symbol: "INTC",
    type: "earnings",
    announcedAt: offsetDays(8, 4, 0).toISOString(),
    timeThai: offsetDays(8, 4, 0).toISOString(),
    importance: "high",
    revenueActual: null,
    revenueForecast: "12.9B",
    revenuePrevious: "12.7B",
    epsActual: null,
    epsForecast: "-0.04",
    epsPrevious: "0.02",
    eventTypeName: "Earnings",
    status: "confirmed",
    source: {
      source: "Intel Investor Relations",
      sourceUrl: "https://www.intc.com/",
      fetchedAt: now.toISOString(),
      timezone: "EST",
    },
  },
  {
    id: "earn-qcom-q3-fy25",
    symbol: "QCOM",
    type: "earnings",
    announcedAt: offsetDays(13, 4, 30).toISOString(),
    timeThai: offsetDays(13, 4, 30).toISOString(),
    importance: "high",
    revenueActual: null,
    revenueForecast: "9.8B",
    revenuePrevious: "9.38B",
    epsActual: null,
    epsForecast: "2.26",
    epsPrevious: "2.33",
    eventTypeName: "Earnings",
    status: "confirmed",
    source: {
      source: "Qualcomm Investor Relations",
      sourceUrl: "https://investor.qualcomm.com/",
      fetchedAt: now.toISOString(),
      timezone: "EST",
    },
  },
  {
    id: "earn-arm-q1-fy26",
    symbol: "ARM",
    type: "earnings",
    announcedAt: offsetDays(16, 4, 30).toISOString(),
    timeThai: offsetDays(16, 4, 30).toISOString(),
    importance: "high",
    revenueActual: null,
    revenueForecast: "940M",
    revenuePrevious: "928M",
    epsActual: null,
    epsForecast: "0.32",
    epsPrevious: "0.30",
    eventTypeName: "Earnings",
    status: "confirmed",
    source: {
      source: "Arm Holdings Investor Relations",
      sourceUrl: "https://investor.arm.com/",
      fetchedAt: now.toISOString(),
      timezone: "EST",
    },
  },
  {
    id: "earn-crwd-q2-fy26",
    symbol: "CRWD",
    type: "earnings",
    announcedAt: offsetDays(18, 4, 30).toISOString(),
    timeThai: offsetDays(18, 4, 30).toISOString(),
    importance: "high",
    revenueActual: null,
    revenueForecast: "958M",
    revenuePrevious: "921M",
    epsActual: null,
    epsForecast: "0.99",
    epsPrevious: "0.93",
    eventTypeName: "Earnings",
    status: "confirmed",
    source: {
      source: "CrowdStrike Investor Relations",
      sourceUrl: "https://ir.crowdstrike.com/",
      fetchedAt: now.toISOString(),
      timezone: "EST",
    },
  },
  {
    id: "earn-pltr-q2-2025",
    symbol: "PLTR",
    type: "earnings",
    announcedAt: offsetDays(10, 21, 0).toISOString(), // Before US market open (BMO)
    timeThai: offsetDays(10, 21, 0).toISOString(),
    importance: "high",
    revenueActual: null,
    revenueForecast: "887M",
    revenuePrevious: "884M",
    epsActual: null,
    epsForecast: "0.09",
    epsPrevious: "0.09",
    eventTypeName: "Earnings",
    status: "confirmed",
    source: {
      source: "Palantir Investor Relations",
      sourceUrl: "https://investors.palantir.com/",
      fetchedAt: now.toISOString(),
      timezone: "EST",
    },
  },
  {
    id: "earn-orcl-q4-fy25",
    symbol: "ORCL",
    type: "earnings",
    announcedAt: offsetDays(20, 4, 0).toISOString(),
    timeThai: offsetDays(20, 4, 0).toISOString(),
    importance: "medium",
    revenueActual: null,
    revenueForecast: "14.6B",
    revenuePrevious: "14.3B",
    epsActual: null,
    epsForecast: "1.65",
    epsPrevious: "1.63",
    eventTypeName: "Earnings",
    status: "confirmed",
    source: {
      source: "Oracle Investor Relations",
      sourceUrl: "https://investor.oracle.com/",
      fetchedAt: now.toISOString(),
      timezone: "EST",
    },
  },
  {
    id: "earn-snow-q2-fy26",
    symbol: "SNOW",
    type: "earnings",
    announcedAt: offsetDays(22, 4, 30).toISOString(),
    timeThai: offsetDays(22, 4, 30).toISOString(),
    importance: "medium",
    revenueActual: null,
    revenueForecast: "899M",
    revenuePrevious: "829M",
    epsActual: null,
    epsForecast: "0.17",
    epsPrevious: "0.14",
    eventTypeName: "Earnings",
    status: "confirmed",
    source: {
      source: "Snowflake Investor Relations",
      sourceUrl: "https://investors.snowflake.com/",
      fetchedAt: now.toISOString(),
      timezone: "EST",
    },
  },
  {
    id: "earn-mrvl-q2-fy26",
    symbol: "MRVL",
    type: "earnings",
    announcedAt: offsetDays(25, 4, 30).toISOString(),
    timeThai: offsetDays(25, 4, 30).toISOString(),
    importance: "high",
    revenueActual: null,
    revenueForecast: "1.87B",
    revenuePrevious: "1.80B",
    epsActual: null,
    epsForecast: "0.58",
    epsPrevious: "0.55",
    eventTypeName: "Earnings",
    status: "confirmed",
    source: {
      source: "Marvell Technology Investor Relations",
      sourceUrl: "https://investor.marvell.com/",
      fetchedAt: now.toISOString(),
      timezone: "EST",
    },
  },

  // ═══════════════════════════════════════════════════════════════
  // SECTION C: INTERNATIONAL TECH EARNINGS
  // ═══════════════════════════════════════════════════════════════
  {
    id: "earn-asml-q2-2025",
    symbol: "ASML",
    type: "earnings",
    announcedAt: offsetDays(4, 14, 0).toISOString(), // Amsterdam time ~14:00 Thai
    timeThai: offsetDays(4, 14, 0).toISOString(),
    importance: "high",
    revenueActual: null,
    revenueForecast: "6.8B EUR",
    revenuePrevious: "5.72B EUR",
    epsActual: null,
    epsForecast: "3.95 EUR",
    epsPrevious: "3.60 EUR",
    eventTypeName: "Earnings",
    guidance: "Full-year 2025 revenue guidance: 30-35B EUR",
    status: "confirmed",
    source: {
      source: "ASML Investor Relations",
      sourceUrl: "https://www.asml.com/en/investors",
      fetchedAt: now.toISOString(),
      timezone: "CET",
    },
  },
  {
    id: "earn-tsm-q2-2025",
    symbol: "TSM",
    type: "earnings",
    announcedAt: offsetDays(1, 6, 0).toISOString(), // Taipei early morning
    timeThai: offsetDays(1, 6, 0).toISOString(),
    importance: "high",
    revenueActual: null,
    revenueForecast: "732.5B NTD",
    revenuePrevious: "673.5B NTD",
    epsActual: null,
    epsForecast: "8.20 NTD",
    epsPrevious: "7.30 NTD",
    eventTypeName: "Earnings",
    guidance: "Q3 2025 revenue guidance: 28.4-29.2B USD",
    status: "confirmed",
    source: {
      source: "TSMC Investor Relations",
      sourceUrl: "https://investor.tsmc.com/",
      fetchedAt: now.toISOString(),
      timezone: "CST (Taiwan)",
    },
  },
  {
    id: "earn-samsung-q2-2025",
    symbol: "005930",
    type: "earnings",
    announcedAt: offsetDays(6, 8, 0).toISOString(), // Seoul 08:00
    timeThai: offsetDays(6, 8, 0).toISOString(),
    importance: "high",
    revenueActual: null,
    revenueForecast: "74.0T KRW",
    revenuePrevious: "71.9T KRW",
    epsActual: null,
    epsForecast: "850 KRW",
    epsPrevious: "780 KRW",
    eventTypeName: "Earnings",
    guidance: "HBM3E ramp-up progress for AI datacenter demand",
    status: "confirmed",
    source: {
      source: "Samsung Electronics Investor Relations",
      sourceUrl: "https://www.samsung.com/global/ir/",
      fetchedAt: now.toISOString(),
      timezone: "KST",
    },
  },
  {
    id: "earn-sap-q2-2025",
    symbol: "SAP",
    type: "earnings",
    announcedAt: offsetDays(9, 14, 0).toISOString(),
    timeThai: offsetDays(9, 14, 0).toISOString(),
    importance: "medium",
    revenueActual: null,
    revenueForecast: "8.55B EUR",
    revenuePrevious: "8.29B EUR",
    epsActual: null,
    epsForecast: "1.22 EUR",
    epsPrevious: "1.17 EUR",
    eventTypeName: "Earnings",
    status: "confirmed",
    source: {
      source: "SAP SE Investor Relations",
      sourceUrl: "https://www.sap.com/investors",
      fetchedAt: now.toISOString(),
      timezone: "CET",
    },
  },

  // ═══════════════════════════════════════════════════════════════
  // SECTION D: DIVIDENDS & CORPORATE EVENTS
  // ═══════════════════════════════════════════════════════════════
  {
    id: "earn-msft-div-xd",
    symbol: "MSFT",
    type: "earnings",
    announcedAt: offsetDays(5, 9, 0).toISOString(),
    timeThai: offsetDays(5, 9, 0).toISOString(),
    importance: "low",
    revenueActual: null,
    revenueForecast: null,
    revenuePrevious: null,
    epsActual: null,
    epsForecast: null,
    epsPrevious: null,
    eventTypeName: "Dividend",
    guidance: "Ex-Dividend Date — $0.83 per share",
    status: "confirmed",
    source: {
      source: "Microsoft Investor Relations",
      sourceUrl: "https://www.microsoft.com/en-us/investor",
      fetchedAt: now.toISOString(),
      timezone: "EST",
    },
  },
  {
    id: "earn-aapl-div-xd",
    symbol: "AAPL",
    type: "earnings",
    announcedAt: offsetDays(18, 9, 0).toISOString(),
    timeThai: offsetDays(18, 9, 0).toISOString(),
    importance: "low",
    revenueActual: null,
    revenueForecast: null,
    revenuePrevious: null,
    epsActual: null,
    epsForecast: null,
    epsPrevious: null,
    eventTypeName: "Dividend",
    guidance: "Ex-Dividend Date — $0.25 per share",
    status: "confirmed",
    source: {
      source: "Apple Investor Relations",
      sourceUrl: "https://investor.apple.com/",
      fetchedAt: now.toISOString(),
      timezone: "EST",
    },
  },
  {
    id: "event-nvda-investor-day",
    symbol: "NVDA",
    type: "earnings",
    announcedAt: offsetDays(30, 22, 0).toISOString(),
    timeThai: offsetDays(30, 22, 0).toISOString(),
    importance: "high",
    revenueActual: null,
    revenueForecast: null,
    revenuePrevious: null,
    epsActual: null,
    epsForecast: null,
    epsPrevious: null,
    eventTypeName: "InvestorDay",
    guidance: "NVIDIA GTC / Technology Showcase — Blackwell Ultra, Rubin roadmap reveal",
    status: "estimated",
    source: {
      source: "NVIDIA Events",
      sourceUrl: "https://www.nvidia.com/gtc/",
      fetchedAt: now.toISOString(),
      timezone: "PST",
    },
  },

  // ═══════════════════════════════════════════════════════════════
  // SECTION E: PAST EVENTS (FOR HISTORICAL REFERENCE)
  // ═══════════════════════════════════════════════════════════════
  {
    id: "earn-tsla-q2-2025-past",
    symbol: "TSLA",
    type: "earnings",
    announcedAt: offsetDays(-3, 4, 0).toISOString(),
    timeThai: offsetDays(-3, 4, 0).toISOString(),
    importance: "high",
    revenueActual: "25.7B",
    revenueForecast: "24.8B",
    revenuePrevious: "25.2B",
    epsActual: "0.52",
    epsForecast: "0.48",
    epsPrevious: "0.45",
    eventTypeName: "Earnings",
    guidance: "Beat EPS by +8.3% · Revenue beat by +3.6%",
    status: "confirmed",
    source: {
      source: "Tesla Investor Relations",
      sourceUrl: "https://ir.tesla.com/",
      fetchedAt: now.toISOString(),
      timezone: "EST",
    },
  },
  {
    id: "econ-gdp-past-q1",
    title: "US GDP (QoQ) — Q1 Final",
    type: "economic",
    importance: "high",
    announcedAt: offsetDays(-5, 20, 30).toISOString(),
    timeThai: offsetDays(-5, 20, 30).toISOString(),
    actual: "2.1%",
    forecast: "1.9%",
    previous: "1.4%",
    revision: null,
    country: "US",
    status: "confirmed",
    source: {
      source: "U.S. Bureau of Economic Analysis",
      sourceUrl: "https://www.bea.gov/",
      fetchedAt: now.toISOString(),
      timezone: "EST",
    },
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// TECH SYMBOL REGISTRY — for filtering and alias resolution
// ─────────────────────────────────────────────────────────────────────────────
export const TECH_SYMBOLS_REGISTRY = {
  US: [
    "NVDA", "AMD", "INTC", "AVGO", "QCOM", "MSFT", "AAPL", "AMZN",
    "GOOGL", "META", "TSLA", "ORCL", "MU", "MRVL", "SMCI", "PLTR",
    "ARM", "CRWD", "SNOW", "TSM",
  ],
  ETF: ["SMH", "SOXX", "QQQ"],
  INTERNATIONAL: [
    "ASML", "ASML.AS", "005930", "005930.KS", "000660", "000660.KS",
    "2454", "2454.TW", "6758", "6758.T", "SAP", "SAP.DE", "SIE", "SIE.DE",
  ],
  /** Symbols explicitly out of scope (Thai stocks) */
  EXCLUDED_BY_DEFAULT: ["AOT", "SCB", "PTT", "CPALL", "ADVANC", "KBANK", "BBL"],
};

/** Returns whether a symbol is in the tech-focused scope */
export function isTechScopeSymbol(symbol: string): boolean {
  const s = symbol.toUpperCase();
  const all = [
    ...TECH_SYMBOLS_REGISTRY.US,
    ...TECH_SYMBOLS_REGISTRY.ETF,
    ...TECH_SYMBOLS_REGISTRY.INTERNATIONAL,
  ];
  return all.some((t) => t.toUpperCase() === s || s.startsWith(t.toUpperCase()));
}

/** Returns true if the symbol is a Thai stock (excluded by default) */
export function isThaiStock(symbol: string): boolean {
  // Thai stocks typically end in .BK or are in the excluded list
  return symbol.endsWith(".BK") || TECH_SYMBOLS_REGISTRY.EXCLUDED_BY_DEFAULT.includes(symbol.toUpperCase());
}
